name: CI/CD for Docker

on:
  push:
    branches: [ "master" ]   # Đổi "master" thành "main" nếu repo mặc định là main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout source
        uses: actions/checkout@v3

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Test login (giúp debug)
      - name: Verify Docker login
