name: CI/CD for Docker

on:
  push:
    branches: [ "master" ]   # hoặc "master" nếu repo bạn dùng master

jobs:
  build:
    runs-on: self-hosted #ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify Docker login
        run: docker info

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/python_todolist:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/python_todolist:latest
        
  deploy:
  #deploy to render.com
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Trigger Render Deploy Hook
  #      run: |
  #        curl -X POST "${{ vars.RENDER_DEPLOY_HOOK }}"
    runs-on: self-hosted  # Bắt buộc phải là self-hosted runner local của bạn

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t anhnguyen1988/python_todolist:latest .
          docker push anhnguyen1988/python_todolist:latest

      - name: Deploy to Minikube
        env:
          KUBECONFIG: /home/actions/.kube/config  # Path kubeconfig của runner local
        run: |
          kubectl set image deployment/python-todolist python-todolist-d6h89=anhnguyen1988/python_todolist:latest
          kubectl rollout status deployment/python-todolist