name: CI/CD for Docker

on:
  push:
    branches: [ "master" ]   # hoặc "master" nếu repo bạn dùng master

jobs:
  build:
    runs-on: [self-hosted, docker-build]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify Docker login
        run: docker info

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/python_todolist:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/python_todolist:latest
        
  deploy:
  #deploy to render.com
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Trigger Render Deploy Hook
  #      run: |
  #        curl -X POST "${{ vars.RENDER_DEPLOY_HOOK }}"
    needs: build  # Chỉ chạy sau khi job build thành công
    runs-on: [self-hosted, minikube]  # Chỉ chạy trên runner có label 'minikube'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Minikube
        env:
          KUBECONFIG: /home/actions/.kube/config
        run: |
          kubectl set image deployment/python-todolist python-todolist-d6h89=anhnguyen1988/python_todolist:latest
          kubectl rollout status deployment/python-todolist