name: CI/CD for Docker

on:
  push:
    branches: [ "master" ]   # hoặc "master" nếu repo của bạn dùng master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout source
        uses: actions/checkout@v3

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Verify Docker login
      - name: Verify Docker login
        run: docker info

      # 4. Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ sec
