name: Deploy Python_ToDoList

on:
  push:
    branches:
      - master  # hoặc nhánh bạn muốn trigger deploy

jobs:
  deploy:
    runs-on: self-hosted  # Bắt buộc phải là self-hosted runner local của bạn

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t anhnguyen1988/python_todolist:latest .
          docker push anhnguyen1988/python_todolist:latest

      - name: Deploy to Minikube
        env:
          KUBECONFIG: /home/actions/.kube/config  # Path kubeconfig của runner local
        run: |
          kubectl set image deployment/python-todolist python-todolist-d6h89=anhnguyen1988/python_todolist:latest
          kubectl rollout status deployment/python-todolist
